### ISSUE TITLE
null issue

### ISSUE THREAD

**Issue by kmfeng** [baoshan/fairy#10]
TypeError: Cannot read property '1' of null
  at /root/cme/node_modules/fairy/lib/fairy.js:461:36
  at /root/cme/node_modules/fairy/node_modules/redis/index.js:1077:13
  at try_callback (/root/cme/node_modules/fairy/node_modules/redis/index.js:532:9)
  at RedisClient.return_reply (/root/cme/node_modules/fairy/node_modules/redis/index.js:614:13)
  at ReplyParser.<anonymous> (/root/cme/node_modules/fairy/node_modules/redis/index.js:266:14)
  at ReplyParser.EventEmitter.emit (events.js:95:17)
  at ReplyParser.send_reply (/root/cme/node_modules/fairy/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/root/cme/node_modules/fairy/node_modules/redis/lib/parser/javascript.js:211:22)
  at RedisClient.on_data (/root/cme/node_modules/fairy/node_modules/redis/index.js:488:27)
  at Socket.<anonymous> (/root/cme/node_modules/fairy/node_modules/redis/index.js:82:14)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)

**Comment by kmfeng** [comment]
TypeError: Cannot read property '1' of null
  at /root/cme/node_modules/fairy/lib/fairy.js:663:33
  at /root/cme/node_modules/fairy/node_modules/redis/index.js:1077:13
  at try_callback (/root/cme/node_modules/fairy/node_modules/redis/index.js:532:9)
  at RedisClient.return_reply (/root/cme/node_modules/fairy/node_modules/redis/index.js:614:13)
  at ReplyParser.<anonymous> (/root/cme/node_modules/fairy/node_modules/redis/index.js:266:14)
  at ReplyParser.EventEmitter.emit (events.js:95:17)
  at ReplyParser.send_reply (/root/cme/node_modules/fairy/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/root/cme/node_modules/fairy/node_modules/redis/lib/parser/javascript.js:211:22)
